### ISSUE TITLE
Recreate Database into Local

### ISSUE THREAD

**Issue by mcabram** [mmacneil/AngularASPNETCore2WebApiAuth#14]
Hi Mr.Mark, thank you for your great work! I've tried the code but I found the EF fails to create new database according to DefaultConnection since I changed the connection to my local database.

Reproduce the problem:
1. I update the DefaultConnection to my local database.
2. I manually delete all files under Migrations and Migrations folder.
3. I run command 'Add-Migration Initial' to create a new migration.
4. I run command 'Update-Database' to create database and tables.
5. But I fail to find the expected new database in my local machine.

Any helps will be highly appreciated!

**Comment by mmacneil** [comment]
What error do you receive?

**Comment by mcabram** [comment]
> What error do you receive?

Dear Mark, thank you for your response. I solved it now. It seems there is a kind of delay in database creation from EF.
