### ISSUE TITLE
how to refresh token after user use app mobile

### ISSUE THREAD

**Issue by MansoorJafari** [mmacneil/AngularASPNETCore2WebApiAuth#3]
Hi
I want create an app for use api my site
all api have authorize attribute 
how to refresh token in mobile?

thanks

**Comment by mmacneil** [comment]
Hi @MansoorJafari - likely too late for you but I just posted an updated tutorial and repository on JWT authentication with refresh tokens in ASP.NET Core Web API.

https://fullstackmark.com/post/19/jwt-authentication-flow-with-refresh-tokens-in-aspnet-core-web-api
https://github.com/mmacneil/AspNetCoreApiStarter
