### ISSUE TITLE
Always generate same token at IssueAt and Expiration

### ISSUE THREAD

**Issue by kevinding0218** [mmacneil/AngularASPNETCore2WebApiAuth#4]
Hello thank you very much for sharing this tutorial and I followed every step, it works great and I like it very much! However, I am not sure it's my error or we need extra implementation that I found each time I login the Auth generates same token information in IssueAt and Expiration field, so if I set my configuration (RequireExpirationTime = true), then after my Expiration of my first time login, my token will always be unauthorized.. Could you please feel free to guide me on that?

Thank you very much!
Ran

**Comment by kevinding0218** [comment]
I have figured out myself, it's because of the JwtIssuerOptions has the default value set for IssueAt.

**Comment by mmacneil** [comment]
Hi Kevin - I've been away the past week but glad you found the answer.

Regards,
Mark
